require 'rails_helper'

RSpec.describe 'Shop Page', type: :system do
  before do
    driven_by(:selenium, using: :headless_chrome, screen_size: [ 1400, 1400 ])
    create_list(:product, 3, category: 'phones')
    create_list(:product, 2, category: 'laptops')
    create(:product, title: 'Discounted Phone', price: 1000, discounted_price: 800, category: 'phones')
  end

  it 'displays products and filters' do
    visit products_path

    expect(page).to have_content('ALL PRODUCTS')
    expect(page).to have_content('FILTERS')
    expect(page).to have_link('All Products')
    expect(page).to have_link('Special Offers')
    expect(page).to have_link('Phones')
    expect(page).to have_link('Laptops')

    # Check product count (3 phones + 2 laptops + 1 discounted phone = 6 total)
    expect(page).to have_selector('[data-testid="product-card"]', count: 6)
  end

  it 'filters by category' do
    visit products_path
    within('aside') do
      click_link 'Phones'
    end

    expect(page).to have_content('PHONES')
    expect(page).to have_selector('[data-testid="product-card"]', count: 4) # 3 regular + 1 discounted
    # Check that a laptop product is NOT present
    # We created 2 laptops, let's assume their titles are generated by factory.
    # But we can't know the exact title easily unless we create them with specific names or check for the category label on the card.
    # The product card shows category in uppercase.
    # Let's check that we don't see 'LAPTOPS' in the product grid area, but it might be hard to scope.
    # Instead, let's just rely on the count and the header 'PHONES'.
  end

  it 'filters by special offers' do
    visit products_path
    click_link 'Special Offers'

    expect(page).to have_content('SPECIAL OFFERS')
    expect(page).to have_content('Discounted Phone')
    expect(page).to have_selector('[data-testid="product-card"]', count: 1)
  end
end
